//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.12 at 08:19:08 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.jackmoxley.com/Moxy", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jackmoxley.moxy.realizer.xml;
